Expose initialization mode
GrepitAB/mcan pull request #41
Opened 2023-10-19 12:31 UTC by vccaedholm

Added initialization_mode method to DynAux trait, to enable software support for disabling of the CAN bus.

Created a new method initialization_mode in reg, similar to configuration_mode but without setting the configuration bit. While CCCR.INIT is set, message transfer from and to the CAN bus is stopped. Setting CCCR.INIT does not change any configuration register.

Exposed the initialization mode by adding the initialization_mode function to the DynAux trait, with will implement a call to the initialization_mode method in reg.

## Thank you!

Thank you for your contribution.
Please make sure that your submission includes the following:

### Must

- [x] The code compiles without `errors` or `warnings`.
- [x] All tests pass and in the best case you also added new tests.
- [x] `cargo +stable fmt` was run.
- [ ] `cargo +stable clippy` yields no `warnings`.
- [x] Your changes were added to the `CHANGELOG.md` in the proper section.
- [x] You add a description of your work to this PR.
- [x] You added proper docs (in code, rustdoc and README.md) for your
      newly added features and code.

2023-10-20 15:12 UTC, Ironedde commented
LGTM, but we should probably merge in #42 to silence the warnings for this patch.

I'll rebase your change once that is in.

2023-10-21 11:14 UTC, nilfit requested changes
Looks like a good addtion, thanks!

2023-10-21 11:14 UTC, nilfit commented on mcan/CHANGELOG.md
> +- Add Can::aux::initialization_mode
```suggestion
- Add `Can::aux::initialization_mode` (#41)
```

2023-10-22 17:11 UTC, glaeqen commented
👍🏻

2023-10-23 15:16 UTC, Ironedde commented
I rebased the branch, the clippy test should now pass.

2023-10-24 07:16 UTC, epontan approved these changes

2023-10-24 07:40 UTC, merged